AllCops:
  TargetRubyVersion: '2.6'
  Exclude:
    - 'bin/**/*'
    - 'Rakefile'
    - 'spec/**/*'
    - 'Gemfile'
    - trifle-ruby.gemspec

Style/Documentation:
  Enabled: false
#
# Layout/LineLength:
#   Max: 80
