inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: '2.6'
  Exclude:
    - 'bin/**/*'
    - 'Rakefile'
    - 'spec/**/*'
    - 'Gemfile'
    - trifle-stats.gemspec

Style/Documentation:
  Enabled: false
